### ISSUE TITLE
[BUG] Players present in the rtf don't get their face replaced

### ISSUE THREAD

**Issue by LeBiquet** [Maradonna90/NewGAN-Manager#183] opened 2023-08-29 19:10 UTC
**Describe the bug**

**To Reproduce**
1. Follow the tutorial. (including the clear cache/show ID etc.)
2. Click on some players
3. See that some players, present in the rtf file, don't get their face replaced

**Comment by Ayal1** [comment] 2023-08-29 20:34
Duplicate of #161

**Closed by Ayal1** 2023-08-29 20:34 UTC
Labels: bug
