### ISSUE TITLE
[BUG] Faces don't update for players with short UID

### ISSUE THREAD

**Issue by twointum** [Maradonna90/NewGAN-Manager#104] opened 2021-12-18 18:34 UTC
**Describe the bug**
[https://imgur.com/upzRIv5](url)
These guys didn't get a face!

**To Reproduce**
Try to add face to these two guys

**Expected behavior**
Those guys to have a face

**Desktop (please complete the following information):**
WIN10

I believe the xml parser is only looking for 7 digit ids and up. Not sure though.

**Comment by Ayal1** [comment] 2021-12-20 16:14
Not bug, that is intended behavior for now

**Comment by Maradonna90** [comment] 2021-12-23 15:03
works as intended so far. The only reason to allow <= 10 digits IDs is for fake players. But for now I like to avoid going lower than seven, because:

1) A super small minority is using the 'fake player' option
2) people might unintentionally overwrite 'real player' faces (although this can be fixed by smart subfolder naming in `graphics`

**Closed by Maradonna90** 2021-12-23 15:03 UTC
Labels: bug
