### ISSUE TITLE
Application has crashed

### ISSUE THREAD

**Issue by Darengard** [Maradonna90/NewGAN-Manager#172] opened 2023-05-20 08:52 UTC
The application wont even start. When I click on the application it instantly tells me the app has crashed. It also shows the following traceback:
Traceback (most recent call last):
  File "\app\newganmanager\__main__.py", line 4, in <module>
    main().main_loop()
  File "\app_packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "\app_packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "\app_packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "\app_packages\toga_winforms\app.py", line 126, in create
    self.interface.startup()
  File "\app\newganmanager\app.py", line 53, in startup
    fh = logging.FileHandler(str(self.paths.app)+'/newgan.log')
  File "logging\__init__.py", line 1147, in __init__
  File "logging\__init__.py", line 1176, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Maradonna (gestalt)\\NewGAN-Manager\\app\\newganmanager\\newgan.log'

I'm on a Windows 10 PC.

Please help. Thanks.

**Comment by Ayal1** [comment] 2023-05-20 09:58
duplicate of #170

**Closed by Ayal1** 2023-05-20 09:58 UTC
Labels: bug
